export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED';
export const RETURN_TO_MAIN = 'RETURN_TO_MAIN';

export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';