export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const REQUEST_WEATHER_PENDING = 'REQUEST_WEATHER_PENDING';
export const REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS';
export const REQUEST_WEATHER_ERROR = 'REQUEST_WEATHER_ERROR';